name: Deploy to Render

on:
  # 1) Despliegue solo tras CI OK y merge a main.
  workflow_run:
    workflows: ["Codacy CI"]
    types:
      - completed

  # 2) Despliegue al crear un tag (release)
  push:
    tags:
      - 'v*.*.*'

jobs:
  # Despliegue tras CI exitoso y push a main (post-merge)
  deploy_after_ci_on_main:
    if: >
      ${{
        github.event_name == 'workflow_run' &&
        github.event.workflow_run.conclusion == 'success' &&
        github.event.workflow_run.event == 'push' &&
        github.event.workflow_run.head_branch == 'main'
      }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Deploy to Render
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"

  # Despliegue cuando se crea un tag vX.Y.Z
  deploy_on_tag:
    if: >
      ${{
        github.event_name == 'push' &&
        startsWith(github.ref, 'refs/tags/v')
      }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Deploy to Render (tag)
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
